#!/usr/bin/env bash

DOT_VIM="https://github.com/dansomething/dot_vim.git"
CMDS="git vim"

echo -n "Checking for required commands..."
for cmd in $CMDS; do
  hash "$cmd" >/dev/null 2>&1 || {
    echo "❌"
    echo "  $cmd command not found. Please install $cmd."
    exit 1
  }
done
echo "✅"

if [ ! -s "$HOME/.homesick/repos/homeshick" ]; then
  echo "Installing Homeshick to manage dotfiles..."
  git clone git://github.com/andsens/homeshick.git "$HOME/.homesick/repos/homeshick"
fi

# shellcheck source=/dev/null
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

# Install dot_vim files
homeshick clone $DOT_VIM
homeshick link dot_vim

if hash nvim >/dev/null 2>&1; then
  echo "Installing providers for neovim..."
  if hash python3 >/dev/null 2>&1; then
    echo "Installing pynvim python3 provider..."
    python3 -m pip install --user --upgrade pynvim --break-system-packages
  fi
  if hash node >/dev/null 2>&1; then
    echo "Installing neovim node provider..."
    npm install -g neovim
  fi
fi
