set nocompatible " be iMproved

" Organizational Tips
" https://vimways.org/2018/from-vimrc-to-vim/

" All of the plugins are installed with vim-plug from this file.
runtime vim-plug.vim
" Platform (Windows, Mac, etc.) configuration.
runtime platforms.vim
" All of the Vim configuration.
runtime config.vim
" All hotkeys, not dependant on plugins, are mapped here.
runtime mappings.vim
" Small custom functions.
runtime functions.vim
" Auto commands.
runtime autocmds.vim
" Attempt to speed up large file handling
runtime largefiles.vim

" Extra local only config that is not committed
let s:extraFile=expand("~/.vim/extra.vim")
if filereadable(s:extraFile)
  exe "source" . s:extraFile
endif
